[tool.isort]
profile = "black"
multi_line_output = 3
order_by_type = false

[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_defs = true
files = "."

[[tool.mypy.overrides]] # Overrides for currently untyped modules
module = [
    "docs.*",
    "docs.ext.*",
    "gitlab.v4.objects.*",
    "setup",
    "tests.functional.*",
    "tests.functional.api.*",
    "tests.unit.*",
    "tests.smoke.*"
]
ignore_errors = true

[[tool.mypy.overrides]] # Overrides to negate above patterns
module = [
    "gitlab.v4.objects.access_requests",
    "gitlab.v4.objects.applications",
    "gitlab.v4.objects.broadcast_messages",
    "gitlab.v4.objects.deployments",
    "gitlab.v4.objects.groups",
    "gitlab.v4.objects.keys",
    "gitlab.v4.objects.merge_requests",
    "gitlab.v4.objects.merge_trains",
    "gitlab.v4.objects.namespaces",
    "gitlab.v4.objects.pages",
    "gitlab.v4.objects.personal_access_tokens",
    "gitlab.v4.objects.project_access_tokens",
    "gitlab.v4.objects.projects",
    "gitlab.v4.objects.tags",
    "gitlab.v4.objects.templates",
    "gitlab.v4.objects.triggers",
    "gitlab.v4.objects.users",
]
ignore_errors = false

[tool.semantic_release]
branch = "main"
version_variable = "gitlab/__version__.py:__version__"
commit_subject = "chore: release v{version}"
commit_message = ""
