name: Test

on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.6
            toxenv: py36
          - python-version: 3.7
            toxenv: py37
          - python-version: 3.8
            toxenv: py38
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox pytest-github-actions-annotate-failures
      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
  functional:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [py_func_v4, py_func_cli]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox pytest-github-actions-annotate-failures
      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
